# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

import sys
from sys import version_info as _swig_python_version_info
print(sys.version)

if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _HIWIN_Python
else:
    import _HIWIN_Python

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def get_current_position_edited(RobotID, num):
    return _HIWIN_Python.get_current_position_edited(RobotID, num)

def connect_robot(address, level):
    return _HIWIN_Python.connect_robot(address, level)

def get_alarm(RobotID):
    return _HIWIN_Python.get_alarm(RobotID)

def set_lin_speed_edited(RobotID, value):
    return _HIWIN_Python.set_lin_speed_edited(RobotID, value)

def get_current_ext_pos_edited(RobotID, num):
    return _HIWIN_Python.get_current_ext_pos_edited(RobotID, num)

def get_RI_all_edited(RobotID, num):
    return _HIWIN_Python.get_RI_all_edited(RobotID, num)

def get_RO_all_edited(RobotID, num):
    return _HIWIN_Python.get_RO_all_edited(RobotID, num)

def get_tool_data_edited(RobotID, num):
    return _HIWIN_Python.get_tool_data_edited(RobotID, num)

def get_base_data_edited(RobotID, num):
    return _HIWIN_Python.get_base_data_edited(RobotID, num)

def ptp_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.ptp_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5)

def ptp_axis_edited(RobotID, mode, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.ptp_axis_edited(RobotID, mode, p0, p1, p2, p3, p4, p5)

def ptp_rel_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.ptp_rel_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5)

def lin_rel_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.ptp_rel_pos_edited(RobotID, mode, p0, p1, p2, p3, p4, p5)

def ptp_rel_axis_edited(RobotID, mode, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.ptp_rel_axis_edited(RobotID, mode, p0, p1, p2, p3, p4, p5)

def lin_pos_edited(RobotID, mode, smooth_value, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.lin_pos_edited(RobotID, mode, smooth_value, p0, p1, p2, p3, p4, p5)

def lin_axis_edited(RobotID, mode, smooth_value, p0, p1, p2, p3, p4, p5):
    return _HIWIN_Python.lin_axis_edited(RobotID, mode, smooth_value, p0, p1, p2, p3, p4, p5)

def set_joint_soft_limit_edited(RobotID, A1_Low, A2_Low, A3_Low, A4_Low, A5_Low, A6_Low, A1_High, A2_High, A3_High, A4_High, A5_High, A6_High):
    return _HIWIN_Python.set_joint_soft_limit_edited(RobotID, A1_Low, A2_Low, A3_Low, A4_Low, A5_Low, A6_Low, A1_High, A2_High, A3_High, A4_High, A5_High, A6_High)

def get_current_joint_edited(RobotID, num):
    return _HIWIN_Python.get_current_joint_edited(RobotID, num)

def callBack(Ae, Be, Ce, De):
    return _HIWIN_Python.callBack(Ae, Be, Ce, De)

def open_connection(address, level, f):
    return _HIWIN_Python.open_connection(address, level, f)

def disconnect(robot):
    return _HIWIN_Python.disconnect(robot)

def set_connection_level(robot, Mode):
    return _HIWIN_Python.set_connection_level(robot, Mode)

def get_connection_level(robot):
    return _HIWIN_Python.get_connection_level(robot)

def get_hrsdk_version(version):
    return _HIWIN_Python.get_hrsdk_version(version)

def set_timer(robot, index, time):
    return _HIWIN_Python.set_timer(robot, index, time)

def get_timer(robot, index):
    return _HIWIN_Python.get_timer(robot, index)

def set_timer_start(robot, index):
    return _HIWIN_Python.set_timer_start(robot, index)

def set_timer_stop(robot, index):
    return _HIWIN_Python.set_timer_stop(robot, index)

def set_timer_name(robot, index, comment):
    return _HIWIN_Python.set_timer_name(robot, index, comment)

def get_timer_name(robot, index, comment, arr_size):
    return _HIWIN_Python.get_timer_name(robot, index, comment, arr_size)

def get_timer_status(robot, index):
    return _HIWIN_Python.get_timer_status(robot, index)

def set_counter(robot, index, co):
    return _HIWIN_Python.set_counter(robot, index, co)

def get_counter(robot, index):
    return _HIWIN_Python.get_counter(robot, index)

def set_pr_type(robot, prNum, coorType):
    return _HIWIN_Python.set_pr_type(robot, prNum, coorType)

def get_pr_type(robot, prNum):
    return _HIWIN_Python.get_pr_type(robot, prNum)

def set_pr_coordinate(robot, prNum, coor):
    return _HIWIN_Python.set_pr_coordinate(robot, prNum, coor)

def get_pr_coordinate(robot, pr, coor):
    return _HIWIN_Python.get_pr_coordinate(robot, pr, coor)

def set_pr_tool_base(robot, prNum, toolNum, baseNum):
    return _HIWIN_Python.set_pr_tool_base(robot, prNum, toolNum, baseNum)

def get_pr_tool_base(robot, pr, tool_base):
    return _HIWIN_Python.get_pr_tool_base(robot, pr, tool_base)

def set_pr(robot, prNum, coorType, coor, ext_pos, tool, base):
    return _HIWIN_Python.set_pr(robot, prNum, coorType, coor, ext_pos, tool, base)

def get_pr(robot, pr_num, coor_type, coor, ext_pos, tool, base):
    return _HIWIN_Python.get_pr(robot, pr_num, coor_type, coor, ext_pos, tool, base)

def remove_pr(robot, pr_num):
    return _HIWIN_Python.remove_pr(robot, pr_num)

def set_pr_comment(robot, index, comment):
    return _HIWIN_Python.set_pr_comment(robot, index, comment)

def get_pr_comment(robot, index, comment, arr_size):
    return _HIWIN_Python.get_pr_comment(robot, index, comment, arr_size)

def get_counter_name(robot, index, name, arr_size):
    return _HIWIN_Python.get_counter_name(robot, index, name, arr_size)

def set_counter_name(robot, index, name):
    return _HIWIN_Python.set_counter_name(robot, index, name)

def set_acc_dec_ratio(robot, acc):
    return _HIWIN_Python.set_acc_dec_ratio(robot, acc)

def get_acc_dec_ratio(robot):
    return _HIWIN_Python.get_acc_dec_ratio(robot)

def set_acc_time(robot, value):
    return _HIWIN_Python.set_acc_time(robot, value)

def get_acc_time(robot):
    return _HIWIN_Python.get_acc_time(robot)

def set_ptp_speed(robot, vel):
    return _HIWIN_Python.set_ptp_speed(robot, vel)

def get_ptp_speed(robot):
    return _HIWIN_Python.get_ptp_speed(robot)

def set_lin_speed(robot, vel):
    return _HIWIN_Python.set_lin_speed(robot, vel)

def get_lin_speed(robot):
    return _HIWIN_Python.get_lin_speed(robot)

def set_override_ratio(robot, vel):
    return _HIWIN_Python.set_override_ratio(robot, vel)

def get_override_ratio(robot):
    return _HIWIN_Python.get_override_ratio(robot)

def get_robot_id(robot, robot_id):
    return _HIWIN_Python.get_robot_id(robot, robot_id)

def set_robot_id(robot, robot_id):
    return _HIWIN_Python.set_robot_id(robot, robot_id)

def set_smooth_length(robot, r):
    return _HIWIN_Python.set_smooth_length(robot, r)

def get_alarm_code(robot, count, alarm_code):
    return _HIWIN_Python.get_alarm_code(robot, count, alarm_code)

def get_alarm_log_count(robot, size):
    return _HIWIN_Python.get_alarm_log_count(robot, size)

def get_alarm_log_msg(robot, idx, msg):
    return _HIWIN_Python.get_alarm_log_msg(robot, idx, msg)

def get_digital_input(robot, index):
    return _HIWIN_Python.get_digital_input(robot, index)

def get_digital_output(robot, index):
    return _HIWIN_Python.get_digital_output(robot, index)

def set_digital_output(robot, index, v):
    return _HIWIN_Python.set_digital_output(robot, index, v)

def get_robot_input(robot, index):
    return _HIWIN_Python.get_robot_input(robot, index)

def get_robot_output(robot, index):
    return _HIWIN_Python.get_robot_output(robot, index)

def set_robot_output(robot, index, v):
    return _HIWIN_Python.set_robot_output(robot, index, v)

def get_valve_output(robot, index):
    return _HIWIN_Python.get_valve_output(robot, index)

def set_valve_output(robot, index, v):
    return _HIWIN_Python.set_valve_output(robot, index, v)

def get_function_input(robot, index):
    return _HIWIN_Python.get_function_input(robot, index)

def get_function_output(robot, index):
    return _HIWIN_Python.get_function_output(robot, index)

def set_DI_simulation_Enable(robot, index, v):
    return _HIWIN_Python.set_DI_simulation_Enable(robot, index, v)

def set_DI_simulation(robot, index, v):
    return _HIWIN_Python.set_DI_simulation(robot, index, v)

def get_DI_simulation_Enable(robot, index):
    return _HIWIN_Python.get_DI_simulation_Enable(robot, index)

def set_digital_input_comment(robot, di_index, comment):
    return _HIWIN_Python.set_digital_input_comment(robot, di_index, comment)

def get_digital_input_comment(robot, di_index, comment, arr_size):
    return _HIWIN_Python.get_digital_input_comment(robot, di_index, comment, arr_size)

def set_digital_output_comment(robot, do_index, comment):
    return _HIWIN_Python.set_digital_output_comment(robot, do_index, comment)

def get_digital_output_comment(robot, do_index, comment, arr_size):
    return _HIWIN_Python.get_digital_output_comment(robot, do_index, comment, arr_size)

def SyncOutput(robot, O_type, O_id, on_off, synMode, delay, distance):
    return _HIWIN_Python.SyncOutput(robot, O_type, O_id, on_off, synMode, delay, distance)

def get_module_input_config(robot, index, sim, value, type, start, end, comment, arr_size):
    return _HIWIN_Python.get_module_input_config(robot, index, sim, value, type, start, end, comment, arr_size)

def get_module_output_config(robot, index, value, type, start, end, comment, arr_size):
    return _HIWIN_Python.get_module_output_config(robot, index, value, type, start, end, comment, arr_size)

def set_module_input_simulation(robot, index, enable):
    return _HIWIN_Python.set_module_input_simulation(robot, index, enable)

def set_module_input_value(robot, index, enable):
    return _HIWIN_Python.set_module_input_value(robot, index, enable)

def set_module_input_start(robot, index, start_number):
    return _HIWIN_Python.set_module_input_start(robot, index, start_number)

def set_module_input_end(robot, index, end_number):
    return _HIWIN_Python.set_module_input_end(robot, index, end_number)

def set_module_input_comment(robot, index, comment):
    return _HIWIN_Python.set_module_input_comment(robot, index, comment)

def set_module_output_value(robot, index, enable):
    return _HIWIN_Python.set_module_output_value(robot, index, enable)

def set_module_output_start(robot, index, start_number):
    return _HIWIN_Python.set_module_output_start(robot, index, start_number)

def set_module_output_end(robot, index, end_number):
    return _HIWIN_Python.set_module_output_end(robot, index, end_number)

def set_module_output_comment(robot, index, comment):
    return _HIWIN_Python.set_module_output_comment(robot, index, comment)

def set_module_input_type(robot, index, type):
    return _HIWIN_Python.set_module_input_type(robot, index, type)

def set_module_output_type(robot, index, type):
    return _HIWIN_Python.set_module_output_type(robot, index, type)

def save_module_io_setting(robot):
    return _HIWIN_Python.save_module_io_setting(robot)

def set_base_number(robot, state):
    return _HIWIN_Python.set_base_number(robot, state)

def get_base_number(robot):
    return _HIWIN_Python.get_base_number(robot)

def define_base(robot, baseNum, coor):
    return _HIWIN_Python.define_base(robot, baseNum, coor)

def get_base_data(robot, num, coor):
    return _HIWIN_Python.get_base_data(robot, num, coor)

def set_tool_number(robot, num):
    return _HIWIN_Python.set_tool_number(robot, num)

def get_tool_number(robot):
    return _HIWIN_Python.get_tool_number(robot)

def define_tool(robot, toolNum, coor):
    return _HIWIN_Python.define_tool(robot, toolNum, coor)

def get_tool_data(robot, num, coor):
    return _HIWIN_Python.get_tool_data(robot, num, coor)

def set_home_point(robot, joint):
    return _HIWIN_Python.set_home_point(robot, joint)

def get_home_point(robot, joint):
    return _HIWIN_Python.get_home_point(robot, joint)

def get_previous_pos(robot, joint):
    return _HIWIN_Python.get_previous_pos(robot, joint)

def enable_joint_soft_limit(v, enable):
    return _HIWIN_Python.enable_joint_soft_limit(v, enable)

def enable_cart_soft_limit(robot, enable):
    return _HIWIN_Python.enable_cart_soft_limit(robot, enable)

def set_joint_soft_limit(robot, low_limit, high_limit):
    return _HIWIN_Python.set_joint_soft_limit(robot, low_limit, high_limit)

def set_cart_soft_limit(robot, low_limit, high_limit):
    return _HIWIN_Python.set_cart_soft_limit(robot, low_limit, high_limit)

def get_joint_soft_limit_config(robot, enable, low_limit, high_limit):
    return _HIWIN_Python.get_joint_soft_limit_config(robot, enable, low_limit, high_limit)

def get_cart_soft_limit_config(robot, enable, low_limit, high_limit):
    return _HIWIN_Python.get_cart_soft_limit_config(robot, enable, low_limit, high_limit)

def confirm_home_point(robot):
    return _HIWIN_Python.confirm_home_point(robot)

def base_calibration(robot, calibrate_type, p0coor, p1coor, p2coor, result_coor):
    return _HIWIN_Python.base_calibration(robot, calibrate_type, p0coor, p1coor, p2coor, result_coor)

def tool_calibration(robot, calibrate_type, p0coor, p1coor, p2coor, p3coor, result_coor):
    return _HIWIN_Python.tool_calibration(robot, calibrate_type, p0coor, p1coor, p2coor, p3coor, result_coor)

def set_rsr(robot, filename, index):
    return _HIWIN_Python.set_rsr(robot, filename, index)

def get_rsr_prog_name(robot, rsr_index, file_name):
    return _HIWIN_Python.get_rsr_prog_name(robot, rsr_index, file_name)

def remove_rsr(robot, index):
    return _HIWIN_Python.remove_rsr(robot, index)

def ext_task_start(robot, mode, select):
    return _HIWIN_Python.ext_task_start(robot, mode, select)

def task_start(robot, task_name):
    return _HIWIN_Python.task_start(robot, task_name)

def task_hold(robot):
    return _HIWIN_Python.task_hold(robot)

def task_continue(robot):
    return _HIWIN_Python.task_continue(robot)

def task_abort(robot):
    return _HIWIN_Python.task_abort(robot)

def get_execute_file_name(robot, file_name):
    return _HIWIN_Python.get_execute_file_name(robot, file_name)

def get_prog_number(robot):
    return _HIWIN_Python.get_prog_number(robot)

def get_prog_name(robot, file_index, file_name):
    return _HIWIN_Python.get_prog_name(robot, file_index, file_name)

def send_file(sock, from_file_path, to_file_path):
    return _HIWIN_Python.send_file(sock, from_file_path, to_file_path)

def download_file(robot, from_file_path, to_file_path):
    return _HIWIN_Python.download_file(robot, from_file_path, to_file_path)

def delete_file(robot, FilePath):
    return _HIWIN_Python.delete_file(robot, FilePath)

def delete_folder(robot, FilePath):
    return _HIWIN_Python.delete_folder(robot, FilePath)

def new_folder(robot, FilePath):
    return _HIWIN_Python.new_folder(robot, FilePath)

def file_rename(robot, oldFilePath, newFilePath):
    return _HIWIN_Python.file_rename(robot, oldFilePath, newFilePath)

def file_drag(robot, fromFilePath, toFilePath):
    return _HIWIN_Python.file_drag(robot, fromFilePath, toFilePath)

def get_hrss_mode(robot):
    return _HIWIN_Python.get_hrss_mode(robot)

def set_motor_state(robot, state):
    return _HIWIN_Python.set_motor_state(robot, state)

def get_motor_state(robot):
    return _HIWIN_Python.get_motor_state(robot)

def set_operation_mode(robot, mode):
    return _HIWIN_Python.set_operation_mode(robot, mode)

def get_operation_mode(robot):
    return _HIWIN_Python.get_operation_mode(robot)

def clear_alarm(robot):
    return _HIWIN_Python.clear_alarm(robot)

def update_hrss(robot, path):
    return _HIWIN_Python.update_hrss(robot, path)

def set_language(srobot, language_number):
    return _HIWIN_Python.set_language(srobot, language_number)

def get_controller_time(robot, year, month, day, hour, minute, second):
    return _HIWIN_Python.get_controller_time(robot, year, month, day, hour, minute, second)

def get_robot_info(s, page_sel, tool_num, base_num, info, is_ready):
    return _HIWIN_Python.get_robot_info(s, page_sel, tool_num, base_num, info, is_ready)

def mastering(robot, joint, type):
    return _HIWIN_Python.mastering(robot, joint, type)

def calibration(robot, joint, type):
    return _HIWIN_Python.calibration(robot, joint, type)

def jog(robot, space_type, index, dir):
    return _HIWIN_Python.jog(robot, space_type, index, dir)

def jog_home(robot):
    return _HIWIN_Python.jog_home(robot)

def jog_stop(robot):
    return _HIWIN_Python.jog_stop(robot)

def ptp_pos(robot, mode, p):
    return _HIWIN_Python.ptp_pos(robot, mode, p)

def ptp_axis(robot, mode, p):
    return _HIWIN_Python.ptp_axis(robot, mode, p)

def ptp_rel_pos(robot, mode, p):
    return _HIWIN_Python.ptp_rel_pos(robot, mode, p)

def ptp_rel_axis(robot, mode, p):
    return _HIWIN_Python.ptp_rel_axis(robot, mode, p)

def ptp_pr(robot, mode, p):
    return _HIWIN_Python.ptp_pr(robot, mode, p)

def ptp_point(s, mode, axis, pos, ext):
    return _HIWIN_Python.ptp_point(s, mode, axis, pos, ext)

def lin_pos(robot, mode, smooth_value, p):
    return _HIWIN_Python.lin_pos(robot, mode, smooth_value, p)

def lin_axis(robot, mode, smooth_value, p):
    return _HIWIN_Python.lin_axis(robot, mode, smooth_value, p)

def lin_rel_pos(robot, mode, smooth_value, p):
    return _HIWIN_Python.lin_rel_pos(robot, mode, smooth_value, p)

def lin_rel_axis(robot, mode, smooth_value, p):
    return _HIWIN_Python.lin_rel_axis(robot, mode, smooth_value, p)

def lin_pr(robot, mode, smooth_value, p):
    return _HIWIN_Python.lin_pr(robot, mode, smooth_value, p)

def circ_pos(robot, mode, p_aux, p_end):
    return _HIWIN_Python.circ_pos(robot, mode, p_aux, p_end)

def circ_axis(robot, mode, p_aux, p_end):
    return _HIWIN_Python.circ_axis(robot, mode, p_aux, p_end)

def circ_pr(robot, mode, p1, p2):
    return _HIWIN_Python.circ_pr(robot, mode, p1, p2)

def motion_hold(robot):
    return _HIWIN_Python.motion_hold(robot)

def motion_continue(robot):
    return _HIWIN_Python.motion_continue(robot)

def motion_abort(robot):
    return _HIWIN_Python.motion_abort(robot)

def motion_delay(robot, delay):
    return _HIWIN_Python.motion_delay(robot, delay)

def set_command_id(robot, id):
    return _HIWIN_Python.set_command_id(robot, id)

def get_command_id(robot):
    return _HIWIN_Python.get_command_id(robot)

def get_command_count(robot):
    return _HIWIN_Python.get_command_count(robot)

def get_motion_state(robot):
    return _HIWIN_Python.get_motion_state(robot)

def remove_command(robot, num):
    return _HIWIN_Python.remove_command(robot, num)

def remove_command_tail(robot, num):
    return _HIWIN_Python.remove_command_tail(robot, num)

def motion_reachable(s, dest_coord, is_reach):
    return _HIWIN_Python.motion_reachable(s, dest_coord, is_reach)

def motion_check_lin(s, coord1, coord2, is_reach):
    return _HIWIN_Python.motion_check_lin(s, coord1, coord2, is_reach)

def get_encoder_count(robot, EncCount):
    return _HIWIN_Python.get_encoder_count(robot, EncCount)

def get_current_joint(robot, joint):
    return _HIWIN_Python.get_current_joint(robot, joint)

def get_current_position(robot, cart):
    return _HIWIN_Python.get_current_position(robot, cart)

def get_position_b0t0(robot, pos):
    return _HIWIN_Python.get_position_b0t0(robot, pos)

def get_current_rpm(robot, rpm):
    return _HIWIN_Python.get_current_rpm(robot, rpm)

def get_device_born_date(robot, YMD):
    return _HIWIN_Python.get_device_born_date(robot, YMD)

def get_operation_time(robot, YMDHm):
    return _HIWIN_Python.get_operation_time(robot, YMDHm)

def get_mileage(robot, mil):
    return _HIWIN_Python.get_mileage(robot, mil)

def get_total_mileage(robot, tomil):
    return _HIWIN_Python.get_total_mileage(robot, tomil)

def get_utilization(robot, utl):
    return _HIWIN_Python.get_utilization(robot, utl)

def get_utilization_ratio(robot, ratio):
    return _HIWIN_Python.get_utilization_ratio(robot, ratio)

def get_motor_torque(robot, cur):
    return _HIWIN_Python.get_motor_torque(robot, cur)

def get_robot_type(robot, robType):
    return _HIWIN_Python.get_robot_type(robot, robType)

def get_hrss_version(robot, ver):
    return _HIWIN_Python.get_hrss_version(robot, ver)

def download_history_zip(s, toFilePath):
    return _HIWIN_Python.download_history_zip(s, toFilePath)

def get_user_alarm_setting_message(robot, num, message):
    return _HIWIN_Python.get_user_alarm_setting_message(robot, num, message)

def set_user_alarm_setting_message(robot, num, message):
    return _HIWIN_Python.set_user_alarm_setting_message(robot, num, message)

def get_payload_config(robot, index, value, comment):
    return _HIWIN_Python.get_payload_config(robot, index, value, comment)

def set_payload_config(robot, index, value, comment):
    return _HIWIN_Python.set_payload_config(robot, index, value, comment)

def get_payload_active(robot, index):
    return _HIWIN_Python.get_payload_active(robot, index)

def set_payload_active(robot, index):
    return _HIWIN_Python.set_payload_active(robot, index)

def get_digital_setting(robot, index, text):
    return _HIWIN_Python.get_digital_setting(robot, index, text)

def set_digital_setting(robot, index, text):
    return _HIWIN_Python.set_digital_setting(robot, index, text)

def set_network_show_msg(s, enable):
    return _HIWIN_Python.set_network_show_msg(s, enable)

def get_network_show_msg(s, flag):
    return _HIWIN_Python.get_network_show_msg(s, flag)

def network_connect(s):
    return _HIWIN_Python.network_connect(s)

def network_disconnect(s):
    return _HIWIN_Python.network_disconnect(s)

def network_send_msg(s, msg):
    return _HIWIN_Python.network_send_msg(s, msg)

def network_recieve_msg(s, msg):
    return _HIWIN_Python.network_recieve_msg(s, msg)

def get_network_config(s, connect_type, ip_addr, port, bracket_type, separator_type, is_format):
    return _HIWIN_Python.get_network_config(s, connect_type, ip_addr, port, bracket_type, separator_type, is_format)

def set_network_config(s, connect_type, ip_addr, port, bracket_type, separator_type, is_format):
    return _HIWIN_Python.set_network_config(s, connect_type, ip_addr, port, bracket_type, separator_type, is_format)

def network_change_ip(s, lan_index, ip_type, ip_addr):
    return _HIWIN_Python.network_change_ip(s, lan_index, ip_type, ip_addr)

def network_get_state(s):
    return _HIWIN_Python.network_get_state(s)

def get_ext_axis_setting(s, index, enable, mode, high_limit, low_limit):
    return _HIWIN_Python.get_ext_axis_setting(s, index, enable, mode, high_limit, low_limit)

def set_ext_axis_setting(s, index, enable, mode, high_limit, low_limit):
    return _HIWIN_Python.set_ext_axis_setting(s, index, enable, mode, high_limit, low_limit)

def get_ext_axis_setting_advanced(s, index, type, math, continuous, int_value, double_value):
    return _HIWIN_Python.get_ext_axis_setting_advanced(s, index, type, math, continuous, int_value, double_value)

def set_ext_axis_setting_advanced(s, index, type, math, continuous, int_value, double_value):
    return _HIWIN_Python.set_ext_axis_setting_advanced(s, index, type, math, continuous, int_value, double_value)

def ext_mastering(s, index):
    return _HIWIN_Python.ext_mastering(s, index)

def get_current_ext_pos(s, pos):
    return _HIWIN_Python.get_current_ext_pos(s, pos)

def get_current_ext_mode(s, mode):
    return _HIWIN_Python.get_current_ext_mode(s, mode)

def set_ext_home_point(robot, ext_pos):
    return _HIWIN_Python.set_ext_home_point(robot, ext_pos)

def get_ext_home_point(robot, ext_pos):
    return _HIWIN_Python.get_ext_home_point(robot, ext_pos)

def get_previous_extpos(robot, ext_pos):
    return _HIWIN_Python.get_previous_extpos(robot, ext_pos)

def ext_ptp_axis(s, mode, p):
    return _HIWIN_Python.ext_ptp_axis(s, mode, p)

def ext_ptp_pos(s, mode, p):
    return _HIWIN_Python.ext_ptp_pos(s, mode, p)

def ext_lin_axis(s, mode, smooth_value, p):
    return _HIWIN_Python.ext_lin_axis(s, mode, smooth_value, p)

def ext_lin_pos(s, mode, smooth_value, p):
    return _HIWIN_Python.ext_lin_pos(s, mode, smooth_value, p)

def ext_asyptp(s, mode, p):
    return _HIWIN_Python.ext_asyptp(s, mode, p)

def set_ext_driver_limit(s, index, enable, inverse, negative_num, positive_num):
    return _HIWIN_Python.set_ext_driver_limit(s, index, enable, inverse, negative_num, positive_num)

def get_ext_driver_limit(s, index, enable, inverse, negative_num, positive_num, N_light, P_light):
    return _HIWIN_Python.get_ext_driver_limit(s, index, enable, inverse, negative_num, positive_num, N_light, P_light)

def get_ext_encoder(s, EncCount):
    return _HIWIN_Python.get_ext_encoder(s, EncCount)

def get_home_warning_setting(s, allow_error_value, allow_near_home):
    return _HIWIN_Python.get_home_warning_setting(s, allow_error_value, allow_near_home)

def set_home_warning_setting(s, allow_error_value, allow_near_home):
    return _HIWIN_Python.set_home_warning_setting(s, allow_error_value, allow_near_home)

def get_DI_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_DI_range(s, from_idx, end_idx, value)

def get_DI_sim_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_DI_sim_range(s, from_idx, end_idx, value)

def get_DI_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_DI_comment_range(s, from_idx, end_idx, str, next_idx)

def get_DO_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_DO_range(s, from_idx, end_idx, value)

def get_DO_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_DO_comment_range(s, from_idx, end_idx, str, next_idx)

def get_FI_all(s, value):
    return _HIWIN_Python.get_FI_all(s, value)

def get_FO_all(s, value):
    return _HIWIN_Python.get_FO_all(s, value)

def get_timer_status_all(s, value):
    return _HIWIN_Python.get_timer_status_all(s, value)

def get_timer_value_all(s, value):
    return _HIWIN_Python.get_timer_value_all(s, value)

def get_timer_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_timer_comment_range(s, from_idx, end_idx, str, next_idx)

def get_counter_value_all(s, value):
    return _HIWIN_Python.get_counter_value_all(s, value)

def get_counter_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_counter_comment_range(s, from_idx, end_idx, str, next_idx)

def get_fieldbus_rs_srw_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_fieldbus_rs_srw_range(s, from_idx, end_idx, value)

def get_fieldbus_rs_srr_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_fieldbus_rs_srr_range(s, from_idx, end_idx, value)

def get_fieldbus_rs_parameter_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_fieldbus_rs_parameter_range(s, from_idx, end_idx, str, next_idx)

def get_fieldbus_rs_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_fieldbus_rs_comment_range(s, from_idx, end_idx, str, next_idx)

def get_system_input_all(s, value, comment):
    return _HIWIN_Python.get_system_input_all(s, value, comment)

def get_system_output_all(s, value, comment):
    return _HIWIN_Python.get_system_output_all(s, value, comment)

def get_MI_config_all(s, sim, value, type, start, end):
    return _HIWIN_Python.get_MI_config_all(s, sim, value, type, start, end)

def get_MI_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_MI_comment_range(s, from_idx, end_idx, str, next_idx)

def get_MO_config_all(s, value, type, start, end):
    return _HIWIN_Python.get_MO_config_all(s, value, type, start, end)

def get_MO_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_MO_comment_range(s, from_idx, end_idx, str, next_idx)

def get_PR_comment_array(s, idx, from_idx, len, str, next_idx):
    return _HIWIN_Python.get_PR_comment_array(s, idx, from_idx, len, str, next_idx)

def get_SI_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_SI_range(s, from_idx, end_idx, value)

def get_SI_sim_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_SI_sim_range(s, from_idx, end_idx, value)

def get_SO_range(s, from_idx, end_idx, value):
    return _HIWIN_Python.get_SO_range(s, from_idx, end_idx, value)

def get_SI_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_SI_comment_range(s, from_idx, end_idx, str, next_idx)

def get_SO_comment_range(s, from_idx, end_idx, str, next_idx):
    return _HIWIN_Python.get_SO_comment_range(s, from_idx, end_idx, str, next_idx)

def get_PR_array(s, idx, from_idx, len, type, pos, tool, base, next_idx):
    return _HIWIN_Python.get_PR_array(s, idx, from_idx, len, type, pos, tool, base, next_idx)

def get_RI_all(s, values):
    return _HIWIN_Python.get_RI_all(s, values)

def get_RO_all(s, values):
    return _HIWIN_Python.get_RO_all(s, values)

def get_VO_all(s, values):
    return _HIWIN_Python.get_VO_all(s, values)

def set_DI_array(s, indexes, values, len):
    return _HIWIN_Python.set_DI_array(s, indexes, values, len)

def set_DI_sim_array(s, indexes, values, len):
    return _HIWIN_Python.set_DI_sim_array(s, indexes, values, len)

def set_DO_array(s, indexes, values, len):
    return _HIWIN_Python.set_DO_array(s, indexes, values, len)

def set_timer_value_array(s, indexes, values, len):
    return _HIWIN_Python.set_timer_value_array(s, indexes, values, len)

def set_counter_array(s, indexes, values, len):
    return _HIWIN_Python.set_counter_array(s, indexes, values, len)

def set_fieldbus_srw_array(s, indexes, values, len):
    return _HIWIN_Python.set_fieldbus_srw_array(s, indexes, values, len)

def set_SI_array(s, indexes, values, len):
    return _HIWIN_Python.set_SI_array(s, indexes, values, len)

def set_SI_sim_array(s, indexes, values, len):
    return _HIWIN_Python.set_SI_sim_array(s, indexes, values, len)

def set_SO_array(s, indexes, values, len):
    return _HIWIN_Python.set_SO_array(s, indexes, values, len)

def set_MO_array(s, indexes, values, len):
    return _HIWIN_Python.set_MO_array(s, indexes, values, len)

def set_VO_array(s, indexes, values, len):
    return _HIWIN_Python.set_VO_array(s, indexes, values, len)

def set_RO_array(s, indexes, values, len):
    return _HIWIN_Python.set_RO_array(s, indexes, values, len)

def get_hrss_sdkver(s, large_ver, small_ver, revision):
    return _HIWIN_Python.get_hrss_sdkver(s, large_ver, small_ver, revision)

def get_hrsdk_sdkver(large_ver, small_ver, revision):
    return _HIWIN_Python.get_hrsdk_sdkver(large_ver, small_ver, revision)

def get_robot_data(robot, sys_info, port_info, axis_info):
    return _HIWIN_Python.get_robot_data(robot, sys_info, port_info, axis_info)

def get_robot_dh(robot, type, dh_value):
    return _HIWIN_Python.get_robot_dh(robot, type, dh_value)

def get_gear_ratio(robot, gear_ratio):
    return _HIWIN_Python.get_gear_ratio(robot, gear_ratio)